### ISSUE TITLE
Link al reporte en el numero de folio

### ISSUE THREAD

**Issue by danny185** [Arvumti/Drenajes#1]
En el panel de administracion de los reportes agregar un link al reporte sobre el numero de folio, para que el administrador pueda visualizarlo.

/admin.php#reportes

![image](https://cloud.githubusercontent.com/assets/10644346/5848166/3144f148-a19b-11e4-9a3d-5592dc929f0c.png)

**Comment by crlome** [comment]
listo :+1:
