### ISSUE TITLE
Mostrar todos los correos enviados

### ISSUE THREAD

**Issue by danny185** [Arvumti/Drenajes#3]
Mostrar todos los correos a los que fue enviada la notificacion del correo nuevo, esto es para que el administrador tenga evidencia a quien se lo envio.

Por ejemplo:
El cliente tiene registrado unicamente 1 correo: a@xxx.com
Pero el reporte se envio ademas a b@xxx.com
Entonces en la lista mostrar ambos correos.

/reportes.php

![image](https://cloud.githubusercontent.com/assets/10644346/5848334/cb5c7a34-a19c-11e4-84ac-11904a88f6b1.png)

**Comment by crlome** [comment]
listo :+1:
