### ISSUE TITLE
Barra azul de menu

### ISSUE THREAD

**Issue by danny185** [Arvumti/Drenajes#8]
![image](https://cloud.githubusercontent.com/assets/10644346/5963797/f122f8f6-a7b4-11e4-9cd7-8d103d3d9ea5.png)

**Comment by Arvumti** [comment]
Listo bro

2015-01-29 12:47 GMT-06:00 Daniel Gallegos <notifications@github.com>:

> [image: image]
> <https://cloud.githubusercontent.com/assets/10644346/5963797/f122f8f6-a7b4-11e4-9cd7-8d103d3d9ea5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arvumti/Drenajes/issues/8>.
>



-- 

 Ing. Jesús Valadez Villegas

Web. www.arvumti.com

Cel. 6181493291

Mail. jesus.valadez@arvumti.com
